ALTER TABLE Tab1 ADD PRIMARY KEY (unique2tab1);
ALTER TABLE Tab2 ADD PRIMARY KEY (unique2tab2);
ALTER TABLE Tab3 ADD PRIMARY KEY (unique2tab3);
ALTER TABLE Tab4 ADD PRIMARY KEY (unique2tab4);
ALTER TABLE Tab5 ADD PRIMARY KEY (unique2tab5);

