ALTER TABLE Tab1st ADD PRIMARY KEY (stringu1tab1);
ALTER TABLE Tab2st ADD PRIMARY KEY (stringu1tab2);
ALTER TABLE Tab3st ADD PRIMARY KEY (stringu1tab3);
ALTER TABLE Tab4st ADD PRIMARY KEY (stringu1tab4);
ALTER TABLE Tab5st ADD PRIMARY KEY (stringu1tab5);
