PREFIX : <http://dblp.l3s.de/d2r/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX dcterms: <http://purl.org/dc/terms/> 

SELECT ?paper ?title 
WHERE { 
 ?paper a :JournalArticle ; dc:title ?title . 
} LIMIT 1000
