PREFIX : <http://awards.org/>
SELECT DISTINCT ?firstName ?lastName 
WHERE {
 ?x :hasReceived ?aw1 ; :hasReceived ?aw2 ; :bornIn ?country ;
 :hasFirstName ?firstName ; :hasLastName ?lastName .
 ?aw1 :hasTitle ?awName1 .
 ?aw2 :hasTitle ?awName2 .
 FILTER ((?aw1 != ?aw2) &&
 (?country != "United States of America") &&
 ((?awName1 = "Academy Award for Best Actor") ||
 (?awName1 = "Academy Award for Best Supporting Actor") ||
 (?awName1 = "Academy Award for Best Actress") ||
 (?awName1 = "Academy Award for Best Supporting Actress")) &&
 ((?awName2 = "Academy Award for Best Actor") || +
 (?awName2 = "Academy Award for Best Supporting Actor") || +
 (?awName2 = "Academy Award for Best Actress") || +
 (?awName2 = "Academy Award for Best Supporting Actress")))
}
