PREFIX : <http://awards.org/> 
SELECT ?fn1 ?ln1 ?fn2 ?ln2 
WHERE { 
 { ?sc1 :hasReceived ?aw1 ; :hasFirstName ?fn1 ; :hasLastName ?ln1 .
   ?aw1 :hasTitle ?awName .
   ?aw1 :receivedIn 1999 .
   ?sc2 :hasReceived ?aw2 ; :hasFirstName ?fn2 ; :hasLastName ?ln2 .
   ?aw2 :hasTitle ?awName .
   ?aw2 :receivedIn 1999 .
   FILTER (?sc1 != ?sc2)
 } UNION {
   ?sc1 :hasReceived ?aw3; :hasFirstName ?fn1 ; :hasLastName ?ln1 .
   ?aw3 :receivedIn ?y .
   ?aw3 :hasTitle "Turing Award" .
   ?sc2 :hasReceived ?aw4 ; :hasFirstName ?fn2 ; :hasLastName ?ln2.
   ?aw4 :receivedIn ?y .
   ?aw4 :hasTitle "Turing Award" .
   FILTER (?sc1 != ?sc2) }
}
