PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> 
PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX rev: <http://purl.org/stuff/rev#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
SELECT ?product ?label 
WHERE { 
    { ?product rdfs:label ?label . 
      ?product bsbm:type bsbm-inst:ProductType162 . 
      ?product bsbm:productFeature bsbm-inst:ProductFeature52 .
      ?product bsbm:productFeature bsbm-inst:ProductFeature897 .
      ?product bsbm:productPropertyNumeric1 ?p1 . 
    FILTER ( ?p1 > 500 ) 
} UNION { 
      ?product rdfs:label ?label . 
      ?product bsbm:type bsbm-inst:ProductType162 .
      ?product bsbm:productFeature bsbm-inst:ProductFeature52 .
      ?product bsbm:productFeature bsbm-inst:ProductFeature913 .
      ?product bsbm:productPropertyNumeric2 ?p2 . 
    FILTER ( ?p2> 50 ) }} 
ORDER BY ?label 
LIMIT 10

