ALTER TABLE Tab1st DROP CONSTRAINT tab1st_pkey;
ALTER TABLE Tab2st DROP CONSTRAINT tab2st_pkey;
ALTER TABLE Tab3st DROP CONSTRAINT tab3st_pkey;
ALTER TABLE Tab4st DROP CONSTRAINT tab4st_pkey;
ALTER TABLE Tab5st DROP CONSTRAINT tab5st_pkey;
