CREATE TEMPORARY TABLE ABOVE24 AS
SELECT SID, dFrom, dTo
FROM (SELECT station_id AS SID,
lag(date_time, 1) OVER (PARTITION BY station_id ORDER BY  date_time) AS dFrom,
date_time AS dTo,
air_temp_set_1 AS currTemp,
ROW_NUMBER() OVER(PARTITION BY station_id ORDER BY date_time) AS rnm
FROM tb_newyorkdata2005) AS a
WHERE currTemp >= 24 AND rnm > 1 AND dTo - dFrom <= interval '1 day';

CREATE TEMPORARY TABLE BOX_ABOVE24 AS 
SELECT SID, (dFrom + interval '24 hours') AS dFrom, dTo 
FROM CoalesceInterval('ABOVE24', 'SID', 'dFrom', 'dTo')
WHERE dTo - dFrom  >= interval '24 hours';

CREATE TEMPORARY TABLE ABOVE41 AS
SELECT SID, dFrom, dTo
FROM (SELECT station_id AS SID,
lag(date_time, 1) OVER (PARTITION BY station_id ORDER BY  date_time) AS dFrom,
date_time AS dTo,
air_temp_set_1 AS currTemp,
ROW_NUMBER() OVER(PARTITION BY station_id ORDER BY date_time) AS rnm
FROM tb_newyorkdata2005) AS a
WHERE currTemp >= 41 AND rnm > 1 AND dTo - dFrom <= interval '1 day';

CREATE TEMPORARY TABLE DIAMOND_ABOVE41 AS 
SELECT SID, dFrom, (dTo + interval '24 hours') AS dTo 
FROM CoalesceInterval('ABOVE41', 'SID', 'dFrom', 'dTo');

CREATE INDEX BOX_ABOVE24_IDX_FROM_TO ON BOX_ABOVE24 (dFrom,dTo);
CREATE INDEX DIAMOND_ABOVE41_IDX_FROM_TO ON DIAMOND_ABOVE41 (dFrom,dTo);

CREATE TEMPORARY TABLE EXCESSIVE_HEAT AS
SELECT BOX_ABOVE24.SID AS SID,
CASE 
WHEN BOX_ABOVE24.dFrom > DIAMOND_ABOVE41.dFrom AND DIAMOND_ABOVE41.dTo > BOX_ABOVE24.dFrom THEN (BOX_ABOVE24.dFrom - interval '24 hours')
WHEN DIAMOND_ABOVE41.dFrom > BOX_ABOVE24.dFrom AND BOX_ABOVE24.dTo > DIAMOND_ABOVE41.dFrom THEN (DIAMOND_ABOVE41.dFrom - interval '24 hours')
WHEN BOX_ABOVE24.dFrom = DIAMOND_ABOVE41.dFrom THEN (BOX_ABOVE24.dFrom - interval '24 hours')
END AS dFrom,
CASE 
WHEN BOX_ABOVE24.dTo < DIAMOND_ABOVE41.dTo AND BOX_ABOVE24.dTo > DIAMOND_ABOVE41.dFrom THEN BOX_ABOVE24.dTo
WHEN DIAMOND_ABOVE41.dTo < BOX_ABOVE24.dTo AND DIAMOND_ABOVE41.dTo > BOX_ABOVE24.dFrom THEN DIAMOND_ABOVE41.dTo
WHEN BOX_ABOVE24.dTo = DIAMOND_ABOVE41.dTo THEN BOX_ABOVE24.dTo
END AS dTo
FROM BOX_ABOVE24, DIAMOND_ABOVE41
WHERE BOX_ABOVE24.SID = DIAMOND_ABOVE41.SID AND 
((BOX_ABOVE24.dFrom > DIAMOND_ABOVE41.dFrom AND DIAMOND_ABOVE41.dTo > BOX_ABOVE24.dFrom) OR (DIAMOND_ABOVE41.dFrom > BOX_ABOVE24.dFrom AND BOX_ABOVE24.dTo > DIAMOND_ABOVE41.dFrom) OR (BOX_ABOVE24.dFrom = DIAMOND_ABOVE41.dFrom)) AND
((BOX_ABOVE24.dTo < DIAMOND_ABOVE41.dTo AND BOX_ABOVE24.dTo > DIAMOND_ABOVE41.dFrom) OR (DIAMOND_ABOVE41.dTo < BOX_ABOVE24.dTo AND DIAMOND_ABOVE41.dTo > BOX_ABOVE24.dFrom) OR (BOX_ABOVE24.dTo = DIAMOND_ABOVE41.dTo));

CREATE TEMPORARY TABLE L1_EH AS 
SELECT county, dFrom, dTo FROM tb_metadata, EXCESSIVE_HEAT WHERE stid = SID
ORDER BY (county, dFrom);

SELECT SID AS county, dFrom, dTo FROM CoalesceInterval('L1_EH', 'county', 'dFrom', 'dTo');
