ALTER TABLE Tab1 DROP CONSTRAINT tab1_pkey;
ALTER TABLE Tab2 DROP CONSTRAINT tab2_pkey;
ALTER TABLE Tab3 DROP CONSTRAINT tab3_pkey;
ALTER TABLE Tab4 DROP CONSTRAINT tab4_pkey;
ALTER TABLE Tab5 DROP CONSTRAINT tab5_pkey;
