CREATE TABLE T_Name (
pid INT NOT NULL PRIMARY KEY,
name VARCHAR(40)
);

CREATE TABLE T_NSCLC (
pid INT NOT NULL PRIMARY KEY,
hosp VARCHAR(40),
stage VARCHAR(40)
);

CREATE TABLE T_SCLC (
pid INT NOT NULL PRIMARY KEY,
hosp VARCHAR(40),
stage VARCHAR(40)
);

ALTER TABLE T_NSCLC
ADD FOREIGN KEY (pid) REFERENCES ID T_Name(pid);

ALTER TABLE T_SCLC
ADD FOREIGN KEY (pid) REFERENCES ID T_Name(pid);

