CREATE TABLE T_Name (
PId INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(40)
);

CREATE TABLE T_NSCLC (
Id INT NOT NULL PRIMARY KEY,
hosp VARCHAR(40),
Stge VARCHAR(40)
);

CREATE TABLE T_SCLC (
key INT NOT NULL PRIMARY KEY,
hosp VARCHAR(40),
St VARCHAR(40)
);

ALTER TABLE T_NSCLC
ADD FOREIGN KEY (Id) REFERENCES ID T_Name(Pid);

ALTER TABLE T_SCLC
ADD FOREIGN KEY (key) REFERENCES ID T_Name(Pid);

