PREFIX : <http://obda.inf.unibz.it/ontop/benchmark/bsbm.owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rev: <http://purl.org/stuff/rev#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX iso3166: <http://downlode.org/rdf/iso-3166/countries#>
PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>

SELECT ?product ?label ?type
WHERE {
  ?product rdfs:label ?label .
  ?product bsbm:type ?type .
  ?product bsbm:productFeature bsbm-inst:ProductFeature78 .
  ?product bsbm:productPropertyNumeric1 ?p1 .
  FILTER ( ?p1 > 500 )
  ?product bsbm:productPropertyNumeric3 ?p3 .
  FILTER (?p3 < 1000 )
  OPTIONAL {
    ?product bsbm:productFeature bsbm-inst:ProductFeature1 .
    ?product rdfs:label ?testVar .
  }
  FILTER (!bound(?testVar))
}

