PREFIX : <http://obda.inf.unibz.it/ontop/benchmark/bsbm.owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rev: <http://purl.org/stuff/rev#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obda: <https://w3id.org/obda/vocabulary#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX iso3166: <http://downlode.org/rdf/iso-3166/countries#>
PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>

SELECT ?id ?review_text ?lang
 {
  	?review a bsbm:Review .	
  	?x bsbm:productId ?id .
  	FILTER (?id < 1000)
	 
 	?product a bsbm:Product .
     OPTIONAL {
 	  ?review bsbm:reviewFor ?product .
           ?review rev:text ?review_text .
 	  FILTER (LANG(?review_text) = 'en')
   	  BIND ("en" AS ?lang) .
     }
     OPTIONAL {
 	  ?review bsbm:reviewFor ?product .
       ?review rev:text ?review_text .
 	  FILTER (LANG(?review_text) = 'zh')
   	  BIND ("zh" AS ?lang) .
     }
     OPTIONAL {
 	  ?review bsbm:reviewFor ?product .
       ?review rev:text ?review_text .
 	  FILTER (LANG(?review_text) = 'de')
   	  BIND ("de" AS ?lang) .
     }
 	FILTER (Bound(?review))
}
