PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX npdv: <http://sws.ifi.uio.no/vocab/npd-v2#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

SELECT DISTINCT ?p1 ?p4 ?p5 WHERE {
  GRAPH ?p1 { <http://sws.ifi.uio.no/data/npd-v2/licence/20108194> a npdv:ProductionLicence . }
  GRAPH ?p4 { ?anon npdv:licenseeInterest "20.000000"^^xsd:decimal . } 
  GRAPH ?p5 { ?anon npdv:licenseeForLicence <http://sws.ifi.uio.no/data/npd-v2/licence/20108194> .} 
}