PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/> 
PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
PREFIX bsbm-inst-prod: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX dc: <http://purl.org/dc/elements/1.1/> 

SELECT
?productFeature ?producer ?propertyTextual1 ?propertyTextual2
?propertyTextual3 ?propertyNumeric1 ?propertyNumeric2 ?propertyTextual5 ?propertyTextual4
?propertyNumeric4 
WHERE {
bsbm-inst-prod:Product5 rdfs:label ?label .
bsbm-inst-prod:Product5 rdfs:comment ?comment .
bsbm-inst-prod:Product5 bsbm:producer ?p .
?p rdfs:label ?producer .
bsbm-inst-prod:Product5 dc:publisher ?p .
bsbm-inst-prod:Product5 bsbm:productFeature ?f .
?f rdfs:label ?productFeature .
bsbm-inst-prod:Product5 bsbm:productPropertyTextual1 ?propertyTextual1 .
bsbm-inst-prod:Product5 bsbm:productPropertyTextual2 ?propertyTextual2 .
bsbm-inst-prod:Product5 bsbm:productPropertyTextual3 ?propertyTextual3 .
bsbm-inst-prod:Product5 bsbm:productPropertyNumeric1 ?propertyNumeric1 .
bsbm-inst-prod:Product5 bsbm:productPropertyNumeric2 ?propertyNumeric2 .
OPTIONAL { bsbm-inst-prod:Product5 bsbm:productPropertyTextual4 ?propertyTextual4 }
OPTIONAL { bsbm-inst-prod:Product5 bsbm:productPropertyTextual5 ?propertyTextual5 }
OPTIONAL { bsbm-inst-prod:Product5 bsbm:productPropertyNumeric4 ?propertyNumeric4 }
}
