-- PREFIX : <http://awards.org/>
-- SELECT ?firstName1 ?lastName1 ?firstName2 ?lastName2 ?awName1 ?awName2
-- WHERE {
--  ?sc1 :hasReceived ?aw1 , ?aw2 ;
--  :hasFirstName ?firstName1 ; :hasLastName ?lastName1 .
--  ?aw1 :receivedIn 2001 ; :hasTitle ?awName1 .
--  ?aw2 :receivedIn 2001 ; :hasTitle ?awName2 .
--  ?sc2 :hasReceived ?aw3 ;
--  :hasFirstName ?firstName2 ; :hasLastName ?lastName2 .
--  ?aw3 :receivedIn 2001 ; :hasTitle ?awName1 .
--  FILTER ((?aw1 != ?aw2) && (?sc1 != ?sc2))
-- }
--
--
-- ans1(firstName1,firstName2,awName1,awName2,lastName1,lastName2)
-- CONSTRUCT [firstName1, firstName2, awName1, awName2, lastName1, lastName2] [firstName1/http://www.w3.org/2001/XMLSchema#string(name_firstm9f12), firstName2/http://www.w3.org/2001/XMLSchema#string(name_firstm9), lastName1/http://www.w3.org/2001/XMLSchema#string(name_lastm9f5), lastName2/http://www.w3.org/2001/XMLSchema#string(name_lastm9), awName1/http://www.w3.org/2001/XMLSchema#string(awa_awardm8f2), awName2/http://www.w3.org/2001/XMLSchema#string(awa_awardm8)]
--    FILTER AND(IS_NOT_NULL(awa_awardm8f2),EQ(awa_awardm8f2,awa_awardm8f2f0))
--       STRICT-FLATTEN awardsm9 -> flat-awards-awards(awards_idxm5,2001,awa_awardm8f2f0)
--          FILTER AND(IS_NOT_NULL(awa_awardm8),NEQ(awards_idxm5f3,awards_idxm5f4))
--             STRICT-FLATTEN awardsm9f8 -> flat-awards-awards(awards_idxm5f4,2001,awa_awardm8)
--                STRICT-FLATTEN awardsm9f8 -> flat-awards-awards(awards_idxm5f3,2001,awa_awardm8f2)
--                   JOIN AND(AND(AND(AND(NEQ(_idm5,_idm5f2),IS_NOT_NULL(name_firstm9f12)),IS_NOT_NULL(name_lastm9f5)),IS_NOT_NULL(name_firstm9)),IS_NOT_NULL(name_lastm9))
--                      EXTENSIONAL awards(_idm5f2,name_firstm9f12,name_lastm9f5,birth_yearm9f7,birth_monthm9f10,birth_daym9f4,bornInm9f11,death_yearm9f0,death_monthm9f3,death_daym9f1,awardsm9f8,sexm9f9,occupationm9f2)
--                      EXTENSIONAL awards(_idm5,name_firstm9,name_lastm9,birth_yearm9,birth_monthm9,birth_daym9,bornInm9,death_yearm9,death_monthm9,death_daym9,awardsm9,sexm9,occupationm9)

-- UNSUPPORTED (CARTESIAN JOIN OR INEQUALITY JOIN) !!